#!/usr/bin/env perl
use strict;
use lib "/home/hosting_locumtest/usr/local/lib/perl5";
use Mojolicious::Lite;
use DBI;
use utf8;
plugin 'mail';

open (DBCONF,"< app.conf") || die "Error open dbconfig file";
my @appconf=<DBCONF>;
close DBCONF;
chomp @appconf;
our $dbh = DBI->connect($appconf[0],$appconf[1],$appconf[2],
			{ PrintError => 1, RaiseError => 1 });
$dbh->{'mysql_enable_utf8'} = 1;
$dbh->do('SET NAMES utf8');

my $subscribe="\nКоманда BonusQuest\nwww.bonusquest.ru";
app->plugin(mail => {
    from     => 'robot@bonusquest.ru',
    encoding => 'base64',
    how      => 'smtp',
    howargs  => ['mail.locum.ru',AuthUser=>$appconf[3],AuthPass=>$appconf[4]],
  });
app->secret($appconf[5]);
app->hook(before_dispatch => sub {
               my $self = shift;
               $self->req->url->base(Mojo::URL->new(q{http://www.bonusquest.ru/}))
	       }
	  );

get '/' => sub {
  my $self = shift;
  my $partners=$dbh->selectrow_array("SELECT COUNT(SHOP.ID) FROM SHOP WHERE SHOP.STATUS=1");
  $self->stash(partners=>$partners);
  $self->render('index');
};

get '/:id' => [id=>qw/\d+/]=> sub{
  my $self=shift;
  my $id=$self->param('id');
  my $quizid=$dbh->selectrow_array("SELECT QUIZ.ID FROM QUIZ LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND SHOP.ID=$id") || 0;
  my $quiz=$dbh->selectall_hashref("SELECT QUIZ.ID,QUIZ.INFO,SHOP.URL,SHOP.NAME AS SHOP FROM QUIZ LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND SHOP.ID=$id",'ID');
  my $question=$dbh->selectall_hashref("SELECT ROUTER.ID AS RID,QUESTION.ID AS QID,QUESTION.CONTENT,QUESTION.TYPE,QUESTION.ANSWERS FROM QUESTION INNER JOIN ROUTER ON QUESTION.ID=ROUTER.QUESTIONID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND SHOP.ID=$id",'RID');
  if(!$quizid){
    $self->stash(capt=>'Бонус не найден',message=>"Здесь пока нет бонусов. Подождем...");
    return $self->render('robot') unless $quizid;
  }
  my @months=('Months','Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь');
  my $selectmonths=[];
  my @lt=localtime;
  my $n=$lt[4]-1;
  for my $i(0..2){#For 3 last months
    $selectmonths->[$i]=[$months[$n],$n];
    $n++;
  }
  $self->session(quizid=>$quizid);
  $self->stash(quiz=>$quiz,
               question=>$question,
               selectmonths=>$selectmonths,
               formmessage=>'',
               questmessage=>'');
  $self->render('quiz');
};

get '/quiz'=>sub{
  my $self=shift;
  my $url=$self->param('url');
  return $self->redirect_to('/') unless $url;
  $url=~s/http:\/\/||shop\.||www\.||store\.//g;#Drop subdomain from URL
  #Regexp utf encoding error
  #if($url !~ /^[А-Яа-яA-Za-z0-9.-]+\.[A-Za-z]{2,4}$/){
  #  $self->stash(message=>'Bad URL >:/');
  #  return $self->render('robot');
  #}
  $url=substr($url,0,50);#Cut url length to 50 char's
  #$dbh->do("INSERT INTO QUERY(URL,SYSDATE) VALUES(\"$url\",NOW())");
  my $quizid=$dbh->selectrow_array("SELECT QUIZ.ID FROM QUIZ LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND SHOP.URL='$url'") || 0;
  my $quiz=$dbh->selectall_hashref("SELECT QUIZ.ID,QUIZ.INFO,SHOP.URL,SHOP.NAME AS SHOP FROM QUIZ LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND SHOP.URL='$url'",'ID');
  my $question=$dbh->selectall_hashref("SELECT ROUTER.ID AS RID,QUESTION.ID AS QID,QUESTION.CONTENT,QUESTION.TYPE,QUESTION.ANSWERS FROM QUESTION INNER JOIN ROUTER ON QUESTION.ID=ROUTER.QUESTIONID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND SHOP.URL='$url'",'RID');
  if(!$quizid){
    $self->stash(capt=>'Бонус не найден',message=>"Магазин $url пока не предоставляет бонусы.");
    return $self->render('robot') unless $quizid;
  }
  my @months=('Months','Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь');
  my $selectmonths=[];
  my @lt=localtime;
  my $n=$lt[4]-1;
  for my $i(0..2){#For 3 last months
    $selectmonths->[$i]=[$months[$n],$n];
    $n++;
  }
  $self->session(quizid=>$quizid);
  $self->stash(quiz=>$quiz,
               question=>$question,
               selectmonths=>$selectmonths,
               formmessage=>'',
               questmessage=>'');
  $self->render('quiz');
};

post '/quiz'=>sub{
  my $self=shift;
  return $self->redirect_to('/') unless $self->session('quizid');#Defend from double refresh
  my $quizid=$self->session('quizid');
  my $param = $self->req->params->to_hash;
  my $answer='';
  my $bonusid='';
  my $sth;
  my @ref;
  my $SQL='';
  my @char=('a'..'z','A'..'Z','1'..'9');
  my $bonuscode='';
  my $formvalidate='';
  my $questvalidate='';
  
  my $quiz=$dbh->selectall_hashref("SELECT QUIZ.ID,QUIZ.INFO,SHOP.URL,SHOP.NAME AS SHOP,SHOP.DESCRIPTION FROM QUIZ LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID LEFT JOIN ROUTER ON QUIZ.ID=ROUTER.QUIZID WHERE QUIZ.STATUS=1 AND QUIZ.ID=$quizid",'ID');
  my $question=$dbh->selectall_hashref("SELECT ROUTER.ID AS RID,QUESTION.ID AS QID,QUESTION.CONTENT,QUESTION.TYPE,QUESTION.ANSWERS FROM QUESTION INNER JOIN ROUTER ON QUESTION.ID=ROUTER.QUESTIONID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE QUIZ.STATUS=1 AND QUIZ.ID=$quizid",'RID');
  my $quizcheck=$dbh->selectall_arrayref("SELECT ROUTER.ID FROM ROUTER WHERE ROUTER.QUIZID=$quizid");
    
  #Validation rules    
  if($param->{'orderdate'} !~/^\d+$/){
      $formvalidate=$formvalidate.'Укажите дату заказа';
  }elsif($param->{'orderdate'}<1 || $param->{'orderdate'}>31){
      $formvalidate=$formvalidate.'Ошибка ввода даты';
  }elsif($param->{'orderemail'} !~/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/){
    $formvalidate=$formvalidate.'Укажите корректный e-mail';
  }elsif(!$param->{'orderaddr'}){
    $formvalidate=$formvalidate.'Введите адрес доставки';
  }elsif(!$param->{'tosagree'}){
    $formvalidate=$formvalidate.'Не приняты условия Пользовательского соглашения';
  }
  foreach my $key(@{$quizcheck}){
    if(!$param->{$key->[0]}){
      $questvalidate='Есть неотвеченные вопросы';
    }
  }  
  
  if(!$formvalidate && !$questvalidate){
    #Generate bonuscode
    foreach(1..8){
      $bonuscode.=$char[int(rand(60))];
    }
    
    #Generate bonus code
    $dbh->do("INSERT INTO BONUS (ID,CODE,STATUS,STATUSDATE,BCREATE,ORDERDATE,ORDERMONTH,ADDRESS,EMAIL) VALUES (NULL,\"$bonuscode\",0,NOW(),NOW(),$param->{'orderdate'},$param->{'ordermonth'},\"$param->{'orderaddr'}\",\"$param->{'orderemail'}\")") || die $dbh->errstr;
    $bonusid=$dbh->last_insert_id('','',"BONUS",'ID');
    $sth=$dbh->prepare("SELECT ROUTER.ID AS RID FROM ROUTER WHERE ROUTER.QUIZID=$quizid");
    $sth->execute;
    
    #Record answer to DB
    while(@ref=$sth->fetchrow_array){
      $answer=join(';',$self->param($ref[0]));
      $dbh->do("INSERT INTO ANSWER (ID,ROUTERID,BONUSID,CONTENT) VALUES (NULL,$ref[0],$bonusid,\"$answer\")") || die $dbh->errstr;
    }

    $self->session(quizid=>0);
    $self->mail(to=>$param->{'orderemail'},
                subject=>"Ваш бонус от магазина ".$quiz->{$quizid}{'URL'},
                data=>"Приветствуем!\n\nВы приняли участие в опросе от магазина ".$quiz->{$quizid}{'SHOP'}." http://".$quiz->{$quizid}{'URL'}.
                "\nВ благодарность за ваши ответы магазин дарит вам бонус: ".$quiz->{$quizid}{'INFO'}."\nВаш бонус-код: $bonuscode (неактивирован)\nБонус будет активирован сразу после обработки данных опроса. Это займет немного времени.\nОб активации бонус-кода мы сразу же вас оповестим.\nСпасибо за то, что вы с нами!\n".$subscribe
                );
    $self->redirect_to('thankyou.html');
  }else{
    
    # Validation is not OK
    my @months=('Months','Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь');
    my $selectmonths=[];
    my @lt=localtime;
    my $n=$lt[4]-1;
    for my $i(0..2){#For 3 last months
      $selectmonths->[$i]=[$months[$n],$n];
      $n++;
    }
    $self->stash(selectmonths=>$selectmonths,
                 formmessage=>$formvalidate,
                 questmessage=>$questvalidate,
                 quiz=>$quiz,
                 question=>$question);
    $self->render('quiz');
  }
};

get '/thankyou'=>sub{
  my $self=shift;
  $self->stash(capt=>'Спасибо за ответы',message=>'Код бонуса отправлен на указанную электронную почту.');
  $self->render('robot');
};

post '/balance'=>sub{
  my $self=shift;
  my $email=$self->param('email');
  return $self->redirect_to('/') unless $email;
  if($email !~ /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/){
    $self->stash(capt=>'Ошибка написания',message=>'Вы неверно указали адрес электронной почты.');
    return $self->render('robot');
  }
  my $balance=$dbh->selectall_arrayref("SELECT BONUS.ID,BONUS.CODE,SHOP.NAME,SHOP.URL,SHOP.DESCRIPTION,QUIZ.INFO FROM BONUS LEFT JOIN ANSWER ON BONUS.ID=ANSWER.BONUSID LEFT JOIN ROUTER ON ANSWER.ROUTERID=ROUTER.ID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE BONUS.STATUS=2 AND BONUS.EMAIL=\"$email\" GROUP BY BONUS.CODE") || undef;
  my $mailmessage='';
  if($balance->[0]){
    $mailmessage="Приветствуем!\nТы или возможно кто-то другой попросил прислать список твоих действующих бонус-кодов.\n\n";
    foreach my $key(@{$balance}){
      $mailmessage=$mailmessage."$key->[2], http://$key->[3]\n$key->[4]\nБонус:$key->[5]\nБонус-код: $key->[1]\n\n";
    }
    $self->mail(to=>$email,
                subject=>'Список действующих бонус-кодов',
                data=>$mailmessage.$subscribe)
  }
  $self->stash(capt=>'Ваш баланс отправлен',message=>'Список подтвержденных бонусов отправлен на указанный адрес электронной почты.');
  $self->render('robot');
};

get '/partners'=>sub{
  my $self=shift;
  my $shop=$dbh->selectall_hashref("SELECT SHOP.ID,SHOP.NAME,SHOP.URL,SHOP.DESCRIPTION,QUIZ.INFO FROM SHOP LEFT JOIN QUIZ ON SHOP.ID=QUIZ.SHOPID WHERE SHOP.STATUS=1 ORDER BY SHOP.URL",'ID');
  $self->stash(shop=>$shop);
  $self->render('partners');
};

post '/sendclaim'=>sub{
  my $self=shift;
  my $bonuscode=$self->param('bonuscode') || 0;
  my $description=$self->param('description');
  my $message='';
  my $bonuscodeid=$dbh->selectrow_array("SELECT BONUS.ID FROM BONUS WHERE CODE='$bonuscode'") || 0;
  if($bonuscodeid){
    $dbh->do("INSERT INTO CLAIM (ID,BONUSID,DESCRIPTION,SDATE) VALUES (NULL,$bonuscodeid,\"$description\",NOW())") || die $dbh->err;
    $message='Спасибо за обращение. Мы сообщим вам о результатах на адрес электронной почты указанный в бонусе.';
  }else{
    $message="Код бонуса <b>$bonuscode</b> неверен. Укажите правильный код.";
  }
  $self->stash(capt=>'Получение претензии',
               message=>$message);
  $self->render('robot');
};

app->start;