#!/usr/bin/env perl
use strict;
use lib "/home/hosting_locumtest/usr/local/lib/perl5";
use Mojolicious::Lite;
use DBI;
use utf8;
plugin 'mail';

open (DBCONF,"< app.conf") || die "Error open dbconfig file";
my @appconf=<DBCONF>;
close DBCONF;
chomp @appconf;
our $dbh = DBI->connect($appconf[0],$appconf[1],$appconf[2],
			{ PrintError => 1, RaiseError => 1 });
$dbh->{'mysql_enable_utf8'} = 1;
$dbh->do('SET NAMES utf8');

my $subscribe="\nКоманда BonusQuest\nwww.bonusquest.ru";
app->plugin(mail => {
    from     => 'robot@bonusquest.ru',
    encoding => 'base64',
    how      => 'smtp',
    howargs  => ['mail.locum.ru',AuthUser=>$appconf[3],AuthPass=>$appconf[4]],
  });
app->secret($appconf[5]);
app->hook(before_dispatch => sub {
               my $self = shift;
               #$self->req->url->base(Mojo::URL->new(q{http://partner.bonusquest.ru/}))
	       }
	  );

get '/' => sub {
  my $self = shift;
	$self->stash(message=>'');
	return $self->redirect_to('/quiz.html') if $self->session('pid');
	$self->render('partner_login');
};

get '/login' => sub {
  my $self = shift;
	$self->stash(message=>'');
  $self->render('partner_login');
};

get '/logout'=>sub{
	my $self=shift;
	$self->session(pid=>'');
	$self->stash(message=>'');
	$self->render('partner_login');
};

post '/auth'=>sub{
  my $self = shift;
  my $param=$self->req->params->to_hash;
  my $pid=$dbh->selectrow_array("SELECT SHOP.ID FROM SHOP WHERE URL=\"$param->{'login'}\" AND PASS=\"$param->{'pass'}\" AND SHOP.STATUS=1") || undef;
  if($pid){
		$self->session(pid=>$pid,
									 url=>$param->{'login'});
		return $self->redirect_to('quiz.html');  
  }
  $self->stash(message=>'Ошибка при вводе логина или пароля');
	$self->render('partner_login');
};

get '/register'=>sub{
	my $self=shift;
	$self->stash(message=>'');
	$self->render('partner_register');
};

post '/register'=>sub{
	my $self=shift;
	my $param=$self->req->params->to_hash;
	$param->{'url'}=~s/(http:\/\/www\.)||(http:\/\/)||(www\.)//g;
	my $message='Укажите адрес магазина';
	my $check=$dbh->selectrow_array("SELECT 1 FROM SHOP WHERE URL=\"$param->{'url'}\" AND SHOP.STATUS=1") || undef;
	$message='Партнер уже зарегистрирован' unless !$check;
	if($param->{'email'} !~ /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/){
		$message='Вы неверно указали адрес электронной почты.';
		$check=1;
	}
	if(!$check && $param->{'url'} && $param->{'email'}){
		#Generate bonuscode
		my @char=('a'..'z','A'..'Z','1'..'9');
		my $pass='';
    foreach(1..8){
      $pass.=$char[int(rand(60))];
    }
		$dbh->do("INSERT INTO SHOP(ID,URL,NAME,EMAIL,PASS,TEL) VALUES(NULL,\"$param->{'url'}\",\"$param->{'name'}\",\"$param->{'email'}\",\"$pass\",\"$param->{'tel'}\")");
		$self->mail(to=>$param->{'email'},
								subject=>'Регистрация партнера',
								data=>"Приветствуем!\nПоздравляем с регистрацией в BonusQuest.\n\nСайт $param->{'name'}, http://$param->{'url'}\n".
"Ваш пароль доступа: $pass\n\nДоступ к партнерской части будет открыт после подтверждения ваших данных.".$subscribe
								);
		$self->stash(capt=>'Спасибо за регистрацию',message=>'Дальнейшие инструкции отправлены на ваш адрес электронной почты.');
		return $self->render('/robot');
	}
	$self->stash(message=>$message);
	$self->render('partner_register');
};

get '/restore'=>sub{
	my $self=shift;
	$self->render('partner_restore');
};

post '/restore'=>sub{
	my $self=shift;
	my $param=$self->req->params->to_hash;
	$param->{'url'}=~s/(http:\/\/www\.)||(http:\/\/)||(www\.)//g;
	my $restore=$dbh->selectrow_arrayref("SELECT SHOP.EMAIL,SHOP.PASS FROM SHOP WHERE URL=\"$param->{'url'}\" AND EMAIL=\"$param->{'email'}\" AND SHOP.STATUS=1") || undef;
	if($restore->[0] && $param->{'url'} && $param->{'email'}){
		$self->mail(to=>$restore->[0],
								subject=>'Восстановление доступа',
								data=>"Приветствуем!\nВы или возможно кто-то другой попросил напомнить пароль доступа: $restore->[1]".$subscribe
								);
	}
	$self->stash(capt=>'Доступ на сайт',message=>'Инструкция о восстановлении пароля отправлена.');
	$self->render('robot');	
};

get '/quiz'=>sub{
	my $self=shift;
	return $self->redirect_to('/login') unless $self->session('pid');
	my $pid=$self->session('pid');
	my $url=$self->session('url');
	my $quiz=$dbh->selectall_hashref("SELECT QUIZ.ID,QUIZ.INFO,QUIZ.STATUS FROM QUIZ WHERE QUIZ.SHOPID=$pid",'ID');
	$self->stash(url=>$url,
							 quiz=>$quiz);
	$self->render('partner_quiz');
};

post '/quiz'=>sub{
	my $self=shift;
	return $self->redirect_to('/login') unless $self->session('pid');
	my $pid=$self->session('pid');
	my $url=$self->session('url');
	my $quizinfo=$self->param('quizinfo');
	$dbh->do("INSERT INTO QUIZ(ID,INFO,SHOPID,QCREATE) VALUES(NULL,\"$quizinfo\",$pid,NOW())") unless !$quizinfo;#Create new quiz
	my $quiz=$dbh->selectall_hashref("SELECT QUIZ.ID,QUIZ.INFO,QUIZ.STATUS FROM QUIZ WHERE QUIZ.SHOPID=$pid",'ID');
	$self->stash(url=>$url,
							 quiz=>$quiz);
	$self->render('partner_quiz');
};

get '/quiz/:id'=>sub{
	my $self=shift;
	return $self->redirect_to('/login') unless $self->session('pid');
	my $pid=$self->session('pid');
	my $url=$self->session('url');
	my $quizid=$self->param('id');
	my $question=$dbh->selectall_hashref("SELECT QUESTION.ID,QUESTION.CONTENT,QUESTION.TYPE,QUESTION.ANSWERS,ROUTER.QUIZID,QUIZ.INFO AS QUIZ FROM QUESTION LEFT JOIN ROUTER ON QUESTION.ID=ROUTER.QUESTIONID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID WHERE QUIZ.ID=$quizid AND QUESTION.SHOPID=$pid",'ID');
	$self->stash(url=>$url,
							 quizid=>$quizid,
							 question=>$question);
	$self->render('partner_question');	
};

post '/quiz/:id'=>sub{
	my $self=shift;
	return $self->redirect_to('/login') unless $self->session('pid');
	my $pid=$self->session('pid');
	my $url=$self->session('url');
	my $quizid=$self->param('id');
	my @questionid=$self->param('questionid');
	my $check=$dbh->selectrow_array("SELECT 1 FROM QUIZ WHERE QUIZ.ID=$quizid AND QUIZ.SHOPID=$pid") || undef;
	if ($check==1){
		$dbh->do("DELETE FROM ROUTER WHERE QUIZID=$quizid");
		foreach my $questionid (@questionid){
			$dbh->do("INSERT INTO ROUTER(ID,QUIZID,QUESTIONID) VALUES(NULL,$quizid,$questionid)");
		};
	};
	my $question=$dbh->selectall_hashref("SELECT QUESTION.ID,QUESTION.CONTENT,QUESTION.TYPE,QUESTION.ANSWERS,ROUTER.QUIZID FROM QUESTION LEFT JOIN ROUTER ON QUESTION.ID=ROUTER.QUESTIONID WHERE QUESTION.SHOPID=$pid",'ID');
	$self->stash(url=>$url,
							 quizid=>$quizid,
							 question=>$question);
	$self->render('partner_question');	
};

get '/bcode'=>sub{
	my $self=shift;
	return $self->redirect_to('/login') unless $self->session('pid');
	my $pid=$self->session('pid');
	my $url=$self->session('url');
	my $param=$self->req->params->to_hash;
	my $search='';
	if($param->{'search'}){
		$search="AND BONUS.CODE=\"$param->{'search'}\"";
	}
	my $bonuses=$dbh->selectall_hashref("SELECT BONUS.ID,DATE(BONUS.BCREATE) AS BCREATE,BONUS.CODE,BONUS.STATUS,BONUS.STATUSDATE,QUIZ.INFO,BONUS.ORDERDATE,BONUS.ORDERMONTH,BONUS.ADDRESS FROM BONUS LEFT JOIN ANSWER ON BONUS.ID=ANSWER.BONUSID LEFT JOIN ROUTER ON ANSWER.ROUTERID=ROUTER.ID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE SHOP.ID=$pid $search GROUP BY BONUS.CODE ORDER BY BONUS.BCREATE",'ID');
	$self->stash(bonuses=>$bonuses,url=>$url);
	$self->render('partner_bcode');
};

post '/bcode'=>sub{
	my $self=shift;
	return $self->redirect_to('/') unless $self->session('pid');
	my $pid=$self->session('pid');
	my $url=$self->session('url');
	my @bid=$self->param('bid');
	my @bonusstatus=$self->param('bonusstatus');
	my $n=0;
	foreach my $key(@bid){
		$dbh->do("UPDATE BONUS SET BONUS.STATUS=$bonusstatus[$n], BONUS.STATUSDATE=NOW() WHERE BONUS.ID=$key");
		$n++;
		#if($bonusstatus[$n]==2){#Verify bonuscode
			#my $respondent=$dbh->selectall_arrayref("SELECT BONUS.EMAIL,DATE(BONUS.BCREATE),BONUS.CODE FROM BONUS WHERE BONUS.ID=$key") || undef;
			#my $respondent=$dbh->selectrow_array("SELECT BONUS.EMAIL FROM BONUS WHERE BONUS.ID=$key") || undef;
			#if($respondent){
			#	$self->mail(to=>$respondent,
			#	          subject=>"Активация бонуса от магазина ".$url,
			#	          data=>"Приветствуем!\n\n$respondent, вы принимали участие в опросе от магазина http://$url".
			#	          "\nВаш бонус-код: $respondent (активирован)\nВы можете указать этот бонус уже при следующей покупке в этом магазине.\nСпасибо за то, что вы с нами!\n".$subscribe
			#	          );
			#}
		#}
	}
	my $bonuses=$dbh->selectall_hashref("SELECT BONUS.ID,DATE(BONUS.BCREATE) AS BCREATE,BONUS.CODE,BONUS.STATUS,BONUS.STATUSDATE,QUIZ.INFO,BONUS.ORDERDATE,BONUS.ORDERMONTH,BONUS.ADDRESS FROM BONUS LEFT JOIN ANSWER ON BONUS.ID=ANSWER.BONUSID LEFT JOIN ROUTER ON ANSWER.ROUTERID=ROUTER.ID LEFT JOIN QUIZ ON ROUTER.QUIZID=QUIZ.ID LEFT JOIN SHOP ON QUIZ.SHOPID=SHOP.ID WHERE SHOP.ID=$pid GROUP BY BONUS.CODE ORDER BY BONUS.BCREATE",'ID');
	$self->stash(bonuses=>$bonuses,url=>$url);
	$self->render('partner_bcode');
};

app->start;